### PR TITLE
Update requirements for latest version of werkzeug

### PR DESCRIPTION
**Pull request by golharam**

### CODE REVIEW

**Review by jasco — DISMISSED** [review]
Thanks.  I'll accept, but I think this is usually generated by pipenv.  I am thinking I must have neglected to refreeze the dependencies when I updated pipenv.  At least until this gets updated again we can go with the range.

**Comment by jasco** [comment]
Actually I didn't realize that the diff was only showing changes against an old commit from over a year ago. Is there a reason you are making these particular changes to a stale fork?  This results in a number of package version regressions.

**Comment by golharam** [comment]
We didn’t want to make changes against an unreleased master branch since this package is being used in an in-house production application, and we need to fix to a specific version. The last released version is tagged as v0.3.2c. So, that’s where we made the changes against.

**Comment by jasco** [comment]
Ah, I see.  I hadn't realized others might be looking at the release tags on this fork so I have not been pushing tags lately.  I will push the current tags, which I have been using in production.   I imagine this will address your immediate needs.  If not I am open to upgrades.

**Comment by golharam** [comment]
How would you like me to apply this patch, if at all?

**Comment by jasco** [comment]
@golharam This patch has been superseded by subsequent commits at least within this fork.  I published tags for the later releases in case anyone is tracking release tags.  Thanks for the pull request.  If the current releases still don't support your requirements maybe you could describe how your requirements differ.  Thanks.

**Pull request closed without merging**
